### PR TITLE
Insert a paragraph summarizing our approach.

### PR DESCRIPTION
**Pull request by danielballan**
I think this paragraph at the top could help orient readers before they dive into our jargon about the different paths.

### CODE REVIEW

**Comment by danielballan** [comment]
It also might be nice to add just a sentence or two about "Motivation" here but I think I had best leave that to others to write.

**Comment by dcwalk** [comment]
Hey @danielballan I think some context is good, I'm wondering tho whether that belongs here? 

I guess I'm trying to think what prior knowledge people have landing at these docs and their goals. Are those details already going to be communicated? Is it just extra text?  

I walked through the harvester/researcher docs with a remote participant today to get a sense of how that works and I think we might want to streamline the amount of text.

Just my thoughts

**Comment by danielballan** [comment]
That's good feedback to have. I found myself wishing for more technical detail about those paths, but the surrounding verbiage can be chopped down without losing info. I'll take a pass at that.

If someone wants to understand our approach (and how it compares to other ongoing efforts) where would they start? Maybe the content of this PR would be more at home on a website that eventually led to this workflow document and the gritty details.

**Comment by dcwalk** [comment]
Yeah, so we have the EDGI event planning section, and I am wondering if there is/should be a Data Refuge one? 

Otherwise if people are at the event I'm assuming presentations/group work covers 'approach'

**Comment by danielballan** [comment]
That makes sense. I had in mind readers who were looking to know more before coming to an event or trying to get up to speed to contribute remotely. But I'm fine declaring this out of scope for this document and closing this PR.

**Pull request closed without merging**
