### PR TITLE
check harvest s3 bucket for the UUID

### PR DESCRIPTION
**Pull request by err0**
If for some reason the harvest URL wasn't populated it's important to double check S3 for the UUID, so that effort isn't wasted harvesting multiple times.

@khdelphine @dcwalk @liblaurie  @titaniumbones review please.

### CODE REVIEW

**Comment by ptressel** [comment]
How about adding a bit more to the instructions, to explain:  If the UUID *is* present in that https://drp-upload.s3.amazonaws.com/ XML info, is there a way to reconstruct the harvest URL, so it can be filled in on the task page?  Is it necessary to also verify that it has been uploaded (and if so, how), or is the presence of the UUID in https://drp-upload.s3.amazonaws.com/ sufficient to believe the data was uploaded?

(I'm looking at a task right now that's in this state, and would really like to verify and fill in the harvest URL, rather than redo the work.)

**Comment by khdelphine** [comment]
Thank you for submitting this improvement suggestion.
 
@b5 & @jschell42 what do you think: it is advisable/feasible for baggers to attempt at locating zip files themselves? I have lost track a bit of how things are organized on the S3 and whether the path can be easily reconstructed.

**Comment by tehsmith** [comment]
So far it seems as though the path can easily be reconstructed like so: https://drp-upload.s3.amazonaws.com/remote/UUID_HERE.zip although access will be denied without AWS credentials.

**Comment by err0** [comment]
sure, I can add a bit more instructions.

**Comment by err0** [comment]
@ptressel added a quick example.

**Comment by dcwalk** [comment]
This looks ready for review...? @khdelphine and @jschell42 could you review? I feel like this is out of my wheelhouse

**Comment by khdelphine** [comment]
I feel that @b5 and @jschell42  should be the ones weighing on this. I have not followed exactly what we are doing in terms of directory structure within the S3 storage.

**Comment by jschell42** [comment]
I'm ok with this as a solution, at least in the short-term. All of the the uploads are going into the "remote" folder so they should be able to construct the URL. They shouldn't need AWS credentials, though, to just construct the URL (only to try to get into the AWS backend).

**Comment by b5** [comment]
There are a few small bugs that can lead to this field not being populated, for the time being I'm a big fan of checking the S3 bucket as a short-term solution. Once we've shipped fixes hopefully this will be less of an issue, but this documentation will always be helpful in my opinion.

**Comment by dcwalk** [comment]
Awesome, so I'm hearing we are good to merge? Will do in the morning unless I get a response otherwise. Thanks all for weighing in

**Comment by khdelphine** [comment]
Thank you for weighing in @b5 and @jschell42.

I just edited the note a bit for clarity.  From my side this is now good to go.

**Comment by dcwalk** [comment]
Merging this in, thank you @err0 @ptressel and @tehsmith for this improvement 👍

**Pull request merged**
