### PR TITLE
Fixed the font size problem and a few more small changes

### LINKED ISSUE #78: add poster crawlable/uncrawlable poster?
do we want to add the poster that lists out things that are crawlable/uncrawlable to the site?

https://drive.google.com/file/d/0B8Gv3Zy5ceY3X0xiSlV2dnhMYWc/view

### PR DESCRIPTION
**Pull request by khdelphine**
*~Including "After the event" and  "Other Useful Documents"~ (will need more discussion)
* Also fixed the font size problem with the lists and the notes.
* Added a few point of details in the Describing document
* Fixed a few more small things.

### CODE REVIEW

**Comment by khdelphine** [comment]
Note @titaniumbones   had requested "After the event"  section in issue 66.

Let me know what you think of the  "Other Useful Documents" section. For now it works as a catch-all, but I think it could be useful to easily expose the users to some key supplemental documents.

**Comment by khdelphine** [comment]
Hey @dcwalk, @librlaurie, or @titaniumbones, could any of you please take a look at this PR if you get a chance? I was hoping it could be merged for this week-end's events. Thanks!

**Comment by dcwalk** [comment]
Hey @khdelphine this is a pretty big set of changes. I'm not sure about the menu structure, and how we want to handle event planning (e.g. Before, after mixed in with workflow)

Also, I'm wondering if the supporting docs might be better inline rather than referenced at the end (e.g. embed the youtube video). It doesn't seem like the material is referenced from the text?

**Comment by dcwalk** [comment]
Maybe we cherry pick out a couple commits into a PR just for integrating the docs and merge the rest?
Also-- I'm expecting a pretty major update to the pre- and post- event work to make it reflect the current process. And I'm wondering if having event planning material in with the workflow docs makes sense?

**Comment by dcwalk** [comment]
Also-- I'm expecting a pretty major update to the pre- and post- event work to make it reflect the current process. And I'm wondering if having event planning material in with the workflow docs makes sense?

**Comment by khdelphine** [comment]
Ok, @dcwalk, clearly some of this needs to be discussed more (which I totally understand). 

In that case I will come up with  a smaller PR. I might not able able to do it until tonight, though.

Thank you for taking the time to look at it.

**Comment by dcwalk** [comment]
Hey @khdelphine, instead of reverting the commits through deletion, why don't we start a new branch for the changes? I'm happy to get that established for review, and can split across a couple PRs that are focused?

**Comment by khdelphine** [comment]
@dcwalk Ah sorry, I did not see your comment until now. I just prepped this PR as a simpler one. Please see if it can be merged now. 

(I have set the deleted files asides so no worries.)

I think personally I could use a new conversation on the next steps with the documentation. Particularly the question of event-specific docs. (Where should they go or not, do they have any place in Workflow or not, etc.) How does that sound?

**Comment by dcwalk** [comment]
Hey, we can (squash) and merge this in, but in general to preserve a clear version history it would be better to start two branches with the small changes you’ve proposed instead of reverting them on this branch.

**Comment by khdelphine** [comment]
Ah ok. I will try to do that next time. 

Thank you for the merge. I just did the gh-deploy and the lists & notes look so much better! :-)

**Pull request merged**
